import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';
import { useMemo, useState } from 'react';

type Branch = { id: number; name: string };
type Row = { id: number; product_name: string; product_sku?: string; category_name?: string; quantity: number; unit_price: string; total: string; cost_snapshot?: string; modifiers?: unknown[]; notes?: string; order: { id: number; folio: string; status: string; channel: string; fulfillment_type: string; payment_method?: string; placed_at?: string; created_at: string; customer_name?: string; branch: Branch } };
type Summary = { sales: number; items: number; orders: number; average_ticket: number; direct_cost: number; profit: number; margin: number; net_profit: number; top_branch: string; top_product: string };

const columns = [
    ['date', 'Fecha'], ['time', 'Hora'], ['order_number', 'Número de pedido'], ['ticket', 'Folio ticket'], ['status', 'Estado pedido'], ['channel', 'Canal'], ['fulfillment', 'Tipo pedido'], ['branch', 'Sucursal'], ['point_of_sale', 'Punto de venta'], ['cash_register', 'Caja'], ['cashier', 'Cajero/usuario'],
    ['category', 'Categoría'], ['product', 'Producto'], ['variant', 'Variante'], ['size', 'Tamaño'], ['quantity', 'Cantidad'], ['customizations', 'Personalizaciones'], ['extras', 'Extras'], ['notes', 'Observaciones'], ['unit_price', 'Precio unitario'], ['unit_discount', 'Descuento unitario'], ['final_unit_price', 'Precio final unitario'], ['sold_total', 'Importe total vendido'],
    ['payment_method', 'Forma pago'], ['card_type', 'Tipo tarjeta'], ['card_last_four', 'Terminación tarjeta'], ['payment_reference', 'Referencia pago'], ['payment_platform', 'Plataforma pago'], ['card_amount', 'Monto tarjeta'], ['cash_amount', 'Monto efectivo'], ['other_amount', 'Monto otros'], ['payment_status', 'Estado pago'],
    ['unit_cost', 'Costo directo unitario'], ['total_cost', 'Costo directo total'], ['sale_unit_price', 'Precio venta unitario'], ['sale_total', 'Venta total'], ['unit_profit', 'Utilidad unitaria'], ['total_profit', 'Utilidad total'], ['profit_margin', 'Margen utilidad %'], ['platform_commission', 'Comisión plataforma'], ['bank_commission', 'Comisión bancaria'], ['bank_income', 'Ingreso cuentas bancarias'], ['applied_discount', 'Descuento aplicado'], ['profit_after_commissions', 'Utilidad después comisiones'], ['margin_after_commissions', 'Margen después comisiones'],
    ['customer', 'Cliente'], ['customer_email', 'Correo cliente'], ['customer_phone', 'Teléfono cliente'],
].map(([id, label]) => ({ id, label }));

const moneyIds = ['unit_price', 'unit_discount', 'final_unit_price', 'sold_total', 'card_amount', 'cash_amount', 'other_amount', 'unit_cost', 'total_cost', 'sale_unit_price', 'sale_total', 'unit_profit', 'total_profit', 'platform_commission', 'bank_commission', 'bank_income', 'applied_discount', 'profit_after_commissions'];
const percentageIds = ['profit_margin', 'margin_after_commissions'];

export default function Index({ rows, branches, summary }: { rows: Row[]; branches: Branch[]; summary: Summary }) {
    const [branchId, setBranchId] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('date'); const [ascending, setAscending] = useState(false); const [visible, setVisible] = useState(columns.map(column => column.id)); const [panel, setPanel] = useState(''); const [selected, setSelected] = useState<Row | null>(null);
    const filtered = useMemo(() => rows.filter(row => (!branchId || String(row.order.branch.id) === branchId) && (!status || row.order.status === status) && (!query || `${row.order.folio} ${row.product_name} ${row.product_sku || ''} ${row.order.customer_name || ''}`.toLowerCase().includes(query.toLowerCase()))).sort((a, b) => { const result = String(valueFor(a, sort)).localeCompare(String(valueFor(b, sort)), 'es', { numeric: true }); return ascending ? result : -result; }), [rows, branchId, status, query, sort, ascending]);
    const activeColumns = columns.filter(column => visible.includes(column.id));
    const metrics: [string, string, string][] = [['Ventas totales', money(summary.sales), 'bg-[#25b85a]'], ['Pedidos', String(summary.orders), 'bg-[#099aa5]'], ['Productos', String(summary.items), 'bg-[#ff7a00]'], ['Ticket prom.', money(summary.average_ticket), 'bg-[#e94250]'], ['Costo directo', money(summary.direct_cost), 'bg-[#062947]'], ['Utilidad', money(summary.profit), 'bg-[#25b85a]'], ['Margen global', `${summary.margin.toFixed(1)}%`, 'bg-[#099aa5]'], ['Utilidad neta', money(summary.net_profit), 'bg-[#ff7a00]'], ['Sucursal top', summary.top_branch, 'bg-[#099aa5]'], ['Producto top', summary.top_product, 'bg-[#e94250]']];
    const exportRows = () => { const content = [activeColumns.map(column => column.label), ...filtered.map(row => activeColumns.map(column => displayValue(row, column.id)))].map(line => line.map(cell => `"${String(cell).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'text/csv;charset=utf-8;' })); link.download = `luzi-ventas-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
    const changeSort = (id: string) => { if (sort === id) setAscending(value => !value); else { setSort(id); setAscending(true); } };

    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI　›　VENTAS</p><h1 className="text-2xl font-black">Ventas</h1></div>}>
        <Head title="Ventas" />
        <div className="space-y-5 p-6 lg:p-8">
            <div className="grid max-w-full grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-5 xl:grid-cols-10">{metrics.map(([label, value, tone]) => <Metric key={label} label={label} value={value} tone={tone} />)}</div>
            <section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><h2 className="mb-4 text-lg font-black">Paneles de ventas</h2><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><PanelButton icon="◷" title="Operación" description="Pedidos activos y preparación" onClick={() => setPanel('operation')} /><PanelButton icon="▤" title="Tickets" description="Tickets y reimpresiones" onClick={() => setPanel('tickets')} /><PanelButton icon="▣" title="Caja" description="Apertura, movimientos y cierre" onClick={() => setPanel('cash')} /><PanelButton icon="▰" title="POS" description="Venta directa en mostrador" onClick={() => setPanel('pos')} /><PanelButton icon="$" title="Pagos" description="Pagos y conciliación" onClick={() => setPanel('payments')} /></div></section>
            <section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><h2 className="mb-4 text-lg font-black">Detalle de ventas por producto</h2>
                <div className="mb-4 flex flex-wrap gap-3 rounded-lg border border-[#e5dfd4] bg-[#fdfcf9] p-3"><label className="grid gap-1 text-xs font-bold text-[#687873]">SUCURSALES<select value={branchId} onChange={event => setBranchId(event.target.value)} className="min-w-48 rounded-lg border border-[#d8d5ce] bg-white px-3 py-2 text-sm"><option value="">Todas</option>{branches.map(branch => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><label className="grid flex-1 gap-1 text-xs font-bold text-[#687873]">BUSCAR<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Folio, producto, SKU o cliente" className="rounded-lg border border-[#d8d5ce] bg-white px-3 py-2 text-sm" /></label><label className="grid gap-1 text-xs font-bold text-[#687873]">ESTADO<select value={status} onChange={event => setStatus(event.target.value)} className="rounded-lg border border-[#d8d5ce] bg-white px-3 py-2 text-sm"><option value="">Todos</option>{['pending', 'preparing', 'ready', 'completed', 'cancelled'].map(value => <option key={value} value={value}>{value}</option>)}</select></label></div>
                <div className="mb-3 flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-black text-[#687873]">{filtered.length} registros filtrados · página 1 de 1</p><div className="flex gap-2"><details className="relative"><summary className="cursor-pointer rounded-lg border border-[#d8d5ce] bg-white px-3 py-2 text-xs font-black uppercase">▼ Columnas visibles</summary><div className="absolute right-0 z-30 mt-2 h-72 w-72 overflow-y-scroll rounded-lg border border-[#d8d5ce] bg-white p-3 shadow-xl">{columns.map(column => <label key={column.id} className="flex items-center gap-2 py-0.5 text-xs font-bold"><input type="checkbox" className="h-4 w-4 accent-[#099aa5]" checked={visible.includes(column.id)} onChange={event => setVisible(event.target.checked ? [...visible, column.id] : visible.filter(id => id !== column.id))} />{column.label}</label>)}</div></details><button type="button" onClick={exportRows} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">⇩ EXCEL</button></div></div>
                <div className="min-h-[420px] overflow-auto rounded-lg border border-[#e5dfd4]"><table className="min-w-max w-full border-separate border-spacing-0 text-left text-sm"><thead className="sticky top-0 z-10 bg-[#fff8ec] text-xs"><tr>{activeColumns.map(column => <th key={column.id} className="whitespace-nowrap border-b border-r border-[#e5dfd4] px-3 py-3"><button type="button" onClick={() => changeSort(column.id)} className="font-black uppercase">{column.label} {sort === column.id ? (ascending ? '↑' : '↓') : '›'}</button></th>)}</tr></thead><tbody>{filtered.map(row => <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer hover:bg-[#f1fcfb]">{activeColumns.map(column => <td key={column.id} className="whitespace-nowrap border-b border-r border-[#edf0ed] px-3 py-3 font-semibold">{displayValue(row, column.id)}</td>)}</tr>)}{!filtered.length && <tr><td colSpan={activeColumns.length} className="p-14 text-center text-[#887e73]">Sin ventas con los filtros seleccionados.</td></tr>}</tbody><tfoot className="sticky bottom-0 bg-[#062947] text-white"><tr>{activeColumns.map((column, index) => <td key={column.id} className="border-r border-white/10 px-3 py-3 text-xs font-black">{footerValue(column.id, index, filtered)}</td>)}</tr></tfoot></table></div>
            </section>
        </div>
        {panel && <SalesPanel panel={panel} rows={filtered} onClose={() => setPanel('')} />}{selected && <DetailDrawer row={selected} onClose={() => setSelected(null)} />}
    </AuthenticatedLayout>;
}

function valueFor(row: Row, id: string): string | number {
    const total = Number(row.total); const price = Number(row.unit_price); const unitCost = Number(row.cost_snapshot || 0); const totalCost = unitCost * row.quantity; const profit = total - totalCost; const margin = total ? profit / total * 100 : 0; const placedAt = row.order.placed_at || row.order.created_at; const payment = row.order.payment_method || '—'; const card = /tarjeta|card/i.test(payment); const cash = /efectivo/i.test(payment);
    return ({ date: new Date(placedAt).toLocaleDateString('es-MX'), time: new Date(placedAt).toLocaleTimeString('es-MX', { hour: '2-digit', minute: '2-digit' }), order_number: row.order.folio, ticket: row.order.folio, status: row.order.status, channel: row.order.channel, fulfillment: row.order.fulfillment_type, branch: row.order.branch.name, point_of_sale: row.order.channel === 'mobile' ? 'App móvil' : 'Mostrador', cash_register: row.order.channel === 'mobile' ? 'Caja app' : 'Caja principal', cashier: row.order.channel === 'mobile' ? 'App móvil LUZI' : 'Administrador', category: row.category_name || '—', product: row.product_name, variant: '—', size: '—', quantity: row.quantity, customizations: row.modifiers?.length || '—', extras: row.modifiers?.length || '—', notes: row.notes || '—', unit_price: price, unit_discount: 0, final_unit_price: price, sold_total: total, payment_method: payment, card_type: card ? 'Tarjeta' : '—', card_last_four: '—', payment_reference: '—', payment_platform: row.order.channel === 'mobile' ? 'LUZI' : '—', card_amount: card ? total : 0, cash_amount: cash ? total : 0, other_amount: !card && !cash && payment !== '—' ? total : 0, payment_status: row.order.status === 'cancelled' ? 'Cancelado' : 'Pagado', unit_cost: unitCost, total_cost: totalCost, sale_unit_price: price, sale_total: total, unit_profit: price - unitCost, total_profit: profit, profit_margin: margin, platform_commission: 0, bank_commission: 0, bank_income: total, applied_discount: 0, profit_after_commissions: profit, margin_after_commissions: margin, customer: row.order.customer_name || 'Cliente móvil', customer_email: '—', customer_phone: '—' } as Record<string, string | number>)[id] ?? '';
}
function displayValue(row: Row, id: string) { const value = valueFor(row, id); return moneyIds.includes(id) ? money(value) : percentageIds.includes(id) ? `${Number(value).toFixed(1)}%` : String(value); }
function footerValue(id: string, index: number, rows: Row[]) { if (index === 0) return 'TOTALES'; if (id === 'quantity') return rows.reduce((sum, row) => sum + row.quantity, 0); if (['sold_total', 'sale_total', 'total_cost', 'total_profit', 'profit_after_commissions', 'card_amount', 'cash_amount', 'other_amount'].includes(id)) return money(rows.reduce((sum, row) => sum + Number(valueFor(row, id)), 0)); return ''; }
function Metric({ label, value, tone }: { label: string; value: string; tone: string }) { return <article className="flex min-h-14 items-center gap-2 rounded-lg border border-[#e5dfd4] bg-white px-2 py-2"><span className={`grid h-7 w-7 place-items-center rounded-md text-sm font-black text-white ${tone}`}>◉</span><span className="min-w-0"><small className="block truncate text-[10px] font-bold uppercase text-[#687873]">{label}</small><b className="block truncate text-base">{value}</b></span></article>; }
function PanelButton({ icon, title, description, onClick }: { icon: string; title: string; description: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="grid min-h-16 grid-cols-[34px_1fr] items-center gap-3 rounded-lg border border-[#e5dfd4] bg-white px-3 text-left hover:border-[#099aa5]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#099aa5] font-black text-white">{icon}</span><span><b className="block text-sm">{title}</b><small className="block text-[11px] text-[#887e73]">{description}</small></span></button>; }
function SalesPanel({ panel, rows, onClose }: { panel: string; rows: Row[]; onClose: () => void }) { const labels: Record<string, string> = { operation: 'Operación', tickets: 'Tickets', cash: 'Caja', pos: 'POS', payments: 'Pagos' }; return <div className="fixed inset-0 z-50 bg-[#062947]/45 p-4"><section className="mx-auto max-w-3xl rounded-xl bg-[#fdfbf6] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">{labels[panel]}</h2><button type="button" onClick={onClose} className="font-black">× CERRAR</button></div><div className="rounded-lg border bg-white p-5 text-sm text-[#52635e]">{panel === 'operation' ? `Pedidos activos: ${rows.filter(row => ['pending', 'preparing', 'ready'].includes(row.order.status)).length}.` : `Registros disponibles en el periodo: ${rows.length}.`}</div></section></div>; }
function DetailDrawer({ row, onClose }: { row: Row; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex justify-end bg-[#062947]/35"><aside className="h-full w-full max-w-md bg-[#fdfbf6] p-6 shadow-2xl"><div className="mb-5 flex justify-between"><h2 className="text-xl font-black">Detalle de venta</h2><button type="button" onClick={onClose} className="font-black">×</button></div><div className="space-y-3 rounded-lg border bg-white p-4 text-sm"><p><b>Pedido:</b> {row.order.folio}</p><p><b>Sucursal:</b> {row.order.branch.name}</p><p><b>Cliente:</b> {row.order.customer_name || 'Cliente móvil'}</p><p><b>Producto:</b> {row.product_name}</p><p><b>Cantidad:</b> {row.quantity}</p><p><b>Importe:</b> {money(row.total)}</p><p><b>Estado:</b> {row.order.status}</p></div><Link href={route('orders.index')} className="mt-5 inline-block rounded-lg bg-[#ffc400] px-4 py-2 text-sm font-black text-[#062947]">ABRIR PEDIDO</Link></aside></div>; }
function money(value: number | string) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(value)); }
