import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head } from '@inertiajs/react';
import { useMemo, useState } from 'react';

type Entry = { id: number; action: string; module: string; entity: string; branch: string; created_at: string; metadata?: Record<string, unknown>; user?: { name: string; email: string } };

export default function Index({ entries }: { entries: Entry[] }) {
    const [query, setQuery] = useState('');
    const visible = useMemo(() => { const value = query.toLowerCase().trim(); return value ? entries.filter(entry => [entry.action, entry.module, entry.entity, entry.branch, entry.user?.name, entry.user?.email].join(' ').toLowerCase().includes(value)) : entries; }, [entries, query]);
    const exportEntries = () => { const rows = [['Fecha', 'Usuario', 'Acción', 'Módulo', 'Entidad', 'Sucursal'], ...visible.map(entry => [date(entry.created_at), entry.user?.name ?? 'Sistema', entry.action, entry.module, entry.entity, entry.branch])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = 'luzi-auditoria.csv'; link.click(); URL.revokeObjectURL(link.href); };
    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI　›　AUDITORÍA</p><h1 className="text-2xl font-black">Auditoría</h1></div>}><Head title="Auditoría" /><div className="p-6 lg:p-8"><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black">Bitácora de auditoría</h2><button type="button" onClick={exportEntries} className="rounded-lg bg-[#099aa5] px-4 py-2 text-xs font-black text-white">⇩　EXPORTAR</button></div><label className="mb-4 flex h-11 items-center gap-2 rounded-lg border border-[#dce2e3] px-3 text-sm"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar en la bitácora" className="w-full border-0 p-0 outline-none ring-0" /></label><div className="overflow-x-auto"><table className="w-full min-w-[1000px] border-separate border-spacing-y-2 text-left text-sm"><thead className="text-xs font-black uppercase text-[#987e6b]"><tr>{['Fecha', 'Usuario', 'Acción', 'Módulo', 'Entidad', 'Sucursal'].map(column => <th className="px-3" key={column}>{column}　›</th>)}</tr></thead><tbody>{visible.length ? visible.map(entry => <tr key={entry.id} className="bg-[#fdfdfd] shadow-sm"><td className="rounded-l-lg px-3 py-3 font-bold">{date(entry.created_at)}</td><td className="px-3 py-3"><strong className="block">{entry.user?.name || 'Sistema'}</strong><small className="text-[#987e6b]">{entry.user?.email || '—'}</small></td><td className="px-3 py-3 font-black capitalize">{entry.action}</td><td className="px-3 py-3 font-black capitalize">{entry.module}</td><td className="px-3 py-3">{entry.entity || '—'}</td><td className="rounded-r-lg px-3 py-3">{entry.branch}</td></tr>) : <tr><td colSpan={6} className="p-14 text-center text-[#887e73]">⚠　Sin registros</td></tr>}</tbody></table></div></section></div></AuthenticatedLayout>;
}
function date(value: string) { return new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
