import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, ReactNode, useState } from 'react';

type Service = { id: number; type: string; provider?: string; account?: string; amount: string; frequency: string; status: string; due_day?: number };
type Branch = { id: number; code: string; name: string; zone?: string; phone?: string; email?: string; address?: string; schedule?: string; manager_name?: string; estimated_prep_minutes: number; allow_scheduled_orders: boolean; latitude?: string; longitude?: string; is_active: boolean; products_count: number; users_count: number; services: Service[] };
type BranchData = { code: string; name: string; zone: string; phone: string; email: string; address: string; schedule: string; manager_name: string; estimated_prep_minutes: string; allow_scheduled_orders: boolean; latitude: string; longitude: string; is_active: boolean };
const emptyBranch: BranchData = { code: '', name: '', zone: '', phone: '', email: '', address: '', schedule: 'Lun-Dom 7:00 a 21:00', manager_name: '', estimated_prep_minutes: '15', allow_scheduled_orders: true, latitude: '', longitude: '', is_active: true };

export default function Index({ branches }: { branches: Branch[] }) {
    const [showNew, setShowNew] = useState(false); const [editing, setEditing] = useState<Branch | null>(null); const [selected, setSelected] = useState<Branch | null>(null); const [servicesOpen, setServicesOpen] = useState(false);
    const createForm = useForm(emptyBranch); const editForm = useForm(emptyBranch); const serviceForm = useForm({ type: 'Internet', provider: '', account: '', service_number: '', amount: '', frequency: 'Mensual', billing_day: '', due_day: '', status: 'active', contact_name: '', contact_phone: '', notes: '' });
    const startEdit = (branch: Branch) => { setEditing(branch); editForm.setData(toData(branch)); };
    const create = (event: FormEvent) => { event.preventDefault(); createForm.post(route('branches.store'), { onSuccess: () => { createForm.reset(); setShowNew(false); } }); };
    const update = (event: FormEvent) => { event.preventDefault(); if (editing) editForm.put(route('branches.update', editing.id), { onSuccess: () => setEditing(null) }); };
    const addService = (event: FormEvent) => { event.preventDefault(); if (selected) serviceForm.post(route('branches.services.store', selected.id), { onSuccess: () => serviceForm.reset() }); };
    const exportBranches = () => { const csv = ['Sucursal,Código,Dirección,Horario,Productos,Estatus', ...branches.map(branch => [branch.name, branch.code, branch.address || '', branch.schedule || '', branch.products_count, branch.is_active ? 'Activo' : 'Inactivo'].map(value => `"${String(value).replaceAll('"', '""')}"`).join(','))].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = 'luzi-sucursales.csv'; link.click(); URL.revokeObjectURL(link.href); };
    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI / SUCURSALES</p><h1 className="text-2xl font-black">Sucursales</h1></div>}>
        <Head title="Sucursales" />
        <div className="p-6 lg:p-8"><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black">Sucursales y puntos de venta</h2><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setServicesOpen(true)} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">▣ VER TABLA DE SERVICIOS</button><button type="button" onClick={exportBranches} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">⇩ EXPORTAR</button><button type="button" onClick={() => setShowNew(true)} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">＋ NUEVA</button></div></div><div className="overflow-auto"><table className="min-w-[1300px] w-full text-left text-sm"><thead className="text-xs text-[#8b7768]"><tr>{['SUCURSAL', 'CÓDIGO', 'DIRECCIÓN', 'HORARIO', 'SERVICIOS', 'PRODUCTOS', 'ACCIONES', 'ESTATUS'].map(column => <th key={column} className="border-b bg-[#fffaf2] px-3 py-3 font-black">{column} ›</th>)}</tr></thead><tbody>{branches.map(branch => <tr key={branch.id} className="border-b border-[#edf0ed] hover:bg-[#f9fcfb]"><td className="px-3 py-4 font-black">{branch.name}</td><td className="px-3 py-4 font-black">{branch.code}</td><td className="max-w-60 px-3 py-4 font-semibold">{branch.address || 'Sin dirección'}</td><td className="px-3 py-4 font-semibold">{branch.schedule || 'Sin horario'}</td><td className="px-3 py-4"><div className="flex items-center gap-2"><span className="whitespace-nowrap text-xs font-black text-[#8b7768]">{money(monthlyServices(branch))} / mes</span><button type="button" onClick={() => setSelected(branch)} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">▣ VER</button></div></td><td className="px-3 py-4 text-center font-black">{branch.products_count}</td><td className="px-3 py-4"><div className="flex min-w-[315px] gap-1"><button type="button" onClick={() => setSelected(branch)} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">▣ ENTRAR A SUCURSAL</button><button type="button" onClick={() => startEdit(branch)} className="rounded-lg bg-[#099aa5] px-3 py-2 text-xs font-black text-white">✎ EDITAR</button><button type="button" onClick={() => { if (confirm(`¿Desactivar ${branch.name}?`)) router.delete(route('branches.deactivate', branch.id)); }} className="rounded-lg border border-[#ffc2c7] px-3 py-2 text-xs font-black text-[#e94250]">♲ ELIMINAR</button></div></td><td className={`px-3 py-4 text-center text-xs font-black ${branch.is_active ? 'text-[#25b85a]' : 'text-[#e94250]'}`}>{branch.is_active ? 'ACTIVO' : 'INACTIVO'}</td></tr>)}{!branches.length && <tr><td colSpan={8} className="p-14 text-center text-[#887e73]">No hay sucursales. Crea la primera para habilitar pickup.</td></tr>}</tbody></table></div></section></div>
        {showNew && <BranchModal title="Nueva sucursal" form={createForm} onSubmit={create} onClose={() => setShowNew(false)} />}{editing && <BranchModal title="Editar sucursal" form={editForm} onSubmit={update} onClose={() => setEditing(null)} />}{selected && <BranchDetail branch={selected} form={serviceForm} onSubmit={addService} onEdit={() => { setSelected(null); startEdit(selected); }} onClose={() => setSelected(null)} />}{servicesOpen && <ServicesMatrix branches={branches} onClose={() => setServicesOpen(false)} />}
    </AuthenticatedLayout>;
}

function BranchModal({ title, form, onSubmit, onClose }: { title: string; form: ReturnType<typeof useForm<BranchData>>; onSubmit: (event: FormEvent) => void; onClose: () => void }) { return <Modal title={title} onClose={onClose}><form onSubmit={onSubmit} className="grid gap-3 md:grid-cols-2"><Field label="Nombre" error={form.errors.name}><input value={form.data.name} onChange={e => form.setData('name', e.target.value)} /></Field><Field label="Código interno" error={form.errors.code}><input value={form.data.code} onChange={e => form.setData('code', e.target.value.toUpperCase())} /></Field><Field label="Dirección" error={form.errors.address}><input value={form.data.address} onChange={e => form.setData('address', e.target.value)} /></Field><Field label="Zona" error={form.errors.zone}><input value={form.data.zone} onChange={e => form.setData('zone', e.target.value)} /></Field><Field label="Teléfono" error={form.errors.phone}><input value={form.data.phone} onChange={e => form.setData('phone', e.target.value)} /></Field><Field label="Correo" error={form.errors.email}><input type="email" value={form.data.email} onChange={e => form.setData('email', e.target.value)} /></Field><Field label="Horario" error={form.errors.schedule}><input value={form.data.schedule} onChange={e => form.setData('schedule', e.target.value)} /></Field><Field label="Responsable" error={form.errors.manager_name}><input value={form.data.manager_name} onChange={e => form.setData('manager_name', e.target.value)} /></Field><Field label="Latitud" error={form.errors.latitude}><input type="number" step="0.0000001" value={form.data.latitude} onChange={e => form.setData('latitude', e.target.value)} /></Field><Field label="Longitud" error={form.errors.longitude}><input type="number" step="0.0000001" value={form.data.longitude} onChange={e => form.setData('longitude', e.target.value)} /></Field><Field label="Preparación (minutos)" error={form.errors.estimated_prep_minutes}><input type="number" min="0" value={form.data.estimated_prep_minutes} onChange={e => form.setData('estimated_prep_minutes', e.target.value)} /></Field><label className="flex items-center gap-2 self-end text-sm font-bold"><input type="checkbox" checked={form.data.is_active} onChange={e => form.setData('is_active', e.target.checked)} /> Sucursal activa</label><label className="col-span-full flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.data.allow_scheduled_orders} onChange={e => form.setData('allow_scheduled_orders', e.target.checked)} /> Permitir pedidos programados</label><div className="col-span-full flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-black">CANCELAR</button><button disabled={form.processing} className="rounded-lg bg-[#099aa5] px-4 py-2 text-sm font-black text-white">GUARDAR</button></div></form></Modal>; }
function BranchDetail({ branch, form, onSubmit, onEdit, onClose }: { branch: Branch; form: ReturnType<typeof useForm>; onSubmit: (event: FormEvent) => void; onEdit: () => void; onClose: () => void }) { return <Modal title={branch.name} onClose={onClose}><div className="mb-5 grid grid-cols-2 gap-3 rounded-lg bg-[#f7f3eb] p-4 text-sm"><p><b>Código:</b> {branch.code}</p><p><b>Responsable:</b> {branch.manager_name || 'Sin asignar'}</p><p><b>Productos:</b> {branch.products_count}</p><p><b>Preparación:</b> {branch.estimated_prep_minutes} min</p></div><div className="mb-5 flex justify-between"><h3 className="font-black">Servicios</h3><b>{money(monthlyServices(branch))} / mes</b></div><div className="mb-4 space-y-2">{branch.services.length ? branch.services.map(service => <div key={service.id} className="flex justify-between rounded-lg border p-3 text-sm"><span><b>{service.type}</b><small className="block text-[#687873]">{service.provider || 'Sin proveedor'} · {service.frequency}</small></span><b>{money(service.amount)}</b></div>) : <p className="rounded-lg border border-dashed p-5 text-center text-sm text-[#887e73]">Sin servicios registrados.</p>}</div><form onSubmit={onSubmit} className="grid gap-2 rounded-lg border bg-white p-4 md:grid-cols-2"><h3 className="col-span-full font-black">Agregar servicio</h3><Field label="Tipo" error={form.errors.type}><input value={form.data.type} onChange={e => form.setData('type', e.target.value)} /></Field><Field label="Proveedor" error={form.errors.provider}><input value={form.data.provider} onChange={e => form.setData('provider', e.target.value)} /></Field><Field label="Monto" error={form.errors.amount}><input type="number" min="0" step="0.01" value={form.data.amount} onChange={e => form.setData('amount', e.target.value)} /></Field><Field label="Frecuencia" error={form.errors.frequency}><select value={form.data.frequency} onChange={e => form.setData('frequency', e.target.value)}><option>Mensual</option><option>Bimestral</option><option>Anual</option></select></Field><div className="col-span-full flex justify-end"><button disabled={form.processing} className="rounded-lg bg-[#099aa5] px-4 py-2 text-xs font-black text-white">AGREGAR SERVICIO</button></div></form><button type="button" onClick={onEdit} className="mt-4 rounded-lg bg-[#ffc400] px-4 py-2 text-sm font-black text-[#062947]">EDITAR SUCURSAL</button></Modal>; }
function ServicesMatrix({ branches, onClose }: { branches: Branch[]; onClose: () => void }) { return <Modal title="Tabla de servicios por sucursal" onClose={onClose}><div className="max-h-[65vh] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-[#fff8ec]"><tr><th className="p-3">Sucursal</th><th className="p-3">Servicio</th><th className="p-3">Proveedor</th><th className="p-3">Monto</th><th className="p-3">Estatus</th></tr></thead><tbody>{branches.flatMap(branch => branch.services.map(service => <tr key={`${branch.id}-${service.id}`} className="border-t"><td className="p-3 font-bold">{branch.name}</td><td className="p-3">{service.type}</td><td className="p-3">{service.provider || '—'}</td><td className="p-3">{money(service.amount)}</td><td className="p-3">{service.status}</td></tr>))}</tbody></table>{!branches.some(branch => branch.services.length) && <p className="p-12 text-center text-[#887e73]">No hay servicios registrados.</p>}</div></Modal>; }
function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#062947]/45 p-4"><section className="mx-auto my-8 w-full max-w-3xl rounded-xl bg-[#fdfbf6] p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button type="button" onClick={onClose} className="text-sm font-black">× CERRAR</button></div>{children}</section></div>; }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="grid gap-1 text-xs font-bold text-[#52635e]">{label}<span className="[&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#d8d5ce] [&>input]:px-3 [&>input]:py-2 [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-[#d8d5ce] [&>select]:px-3 [&>select]:py-2">{children}</span><span className="min-h-4 text-[#e94250]">{error}</span></label>; }
function toData(branch: Branch): BranchData { return { code: branch.code, name: branch.name, zone: branch.zone || '', phone: branch.phone || '', email: branch.email || '', address: branch.address || '', schedule: branch.schedule || '', manager_name: branch.manager_name || '', estimated_prep_minutes: String(branch.estimated_prep_minutes || 15), allow_scheduled_orders: branch.allow_scheduled_orders, latitude: branch.latitude || '', longitude: branch.longitude || '', is_active: branch.is_active }; }
function monthlyServices(branch: Branch) { return branch.services.filter(service => service.status === 'active').reduce((total, service) => total + Number(service.amount) / (service.frequency === 'Bimestral' ? 2 : service.frequency === 'Anual' ? 12 : 1), 0); }
function money(value: number | string) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(value)); }
