import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type ReportRow = { report: string; value: number; currency: boolean };
type Product = { id: number; name: string; price: number; cost: number; margin: number };

export default function Index({ filters, reportRows, profitability }: { filters: { from: string; to: string }; reportRows: ReportRow[]; profitability: Product[] }) {
    const [from, setFrom] = useState(filters.from); const [to, setTo] = useState(filters.to);
    const submit = (event: FormEvent) => { event.preventDefault(); router.get(route('reports.index'), { from, to }, { preserveState: true }); };
    const exportReport = () => { const rows = [['Reporte', 'Valor'], ...reportRows.map(row => [row.report, row.value]), [], ['Producto', 'Precio', 'Costo', 'Margen'], ...profitability.map(row => [row.name, row.price, row.cost, `${row.margin.toFixed(2)}%`])]; const csv = rows.map(row => row.map(value => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = 'luzi-reportes.csv'; link.click(); URL.revokeObjectURL(link.href); };
    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI　›　REPORTES</p><h1 className="text-2xl font-black">Reportes</h1></div>}><Head title="Reportes" /><div className="space-y-5 p-6 lg:p-8"><form onSubmit={submit} className="flex flex-wrap items-end gap-3 rounded-xl border border-[#e5dfd4] bg-white p-4"><label className="grid gap-1 text-xs font-black text-[#987e6b]">DESDE<input type="date" value={from} onChange={event => setFrom(event.target.value)} className="rounded-lg border-[#d8d5ce]" /></label><label className="grid gap-1 text-xs font-black text-[#987e6b]">HASTA<input type="date" value={to} onChange={event => setTo(event.target.value)} className="rounded-lg border-[#d8d5ce]" /></label><button className="rounded-lg bg-[#099aa5] px-4 py-2 text-sm font-black text-white">ACTUALIZAR</button></form><div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">Reportes exportables</h2><button type="button" onClick={exportReport} className="rounded-lg bg-[#099aa5] px-4 py-2 text-xs font-black text-white">⇩　EXPORTAR</button></div><div className="overflow-x-auto"><table className="w-full min-w-[520px] border-separate border-spacing-y-2 text-left text-sm"><thead className="text-xs font-black uppercase text-[#987e6b]"><tr><th className="px-3">REPORTE　›</th><th className="px-3">VALOR　›</th></tr></thead><tbody>{reportRows.map(row => <tr key={row.report} className="bg-[#fdfdfd] shadow-sm"><td className="rounded-l-lg px-3 py-3 font-black">{row.report}</td><td className="rounded-r-lg px-3 py-3 font-black">{row.currency ? money(row.value) : row.value}</td></tr>)}</tbody></table></div></section><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><h2 className="mb-5 text-lg font-black">Rentabilidad por producto</h2><div className="max-h-[640px] overflow-auto"><table className="w-full min-w-[620px] border-separate border-spacing-y-2 text-left text-sm"><thead className="sticky top-0 bg-white text-xs font-black uppercase text-[#987e6b]"><tr><th className="px-3">PRODUCTO　›</th><th className="px-3">PRECIO　›</th><th className="px-3">COSTO　›</th><th className="px-3">MARGEN　›</th></tr></thead><tbody>{profitability.length ? profitability.map(product => <tr key={product.id} className="bg-[#fdfdfd] shadow-sm"><td className="rounded-l-lg px-3 py-3 font-black">{product.name}</td><td className="px-3 py-3 font-black">{money(product.price)}</td><td className="px-3 py-3 font-black">{money(product.cost)}</td><td className="rounded-r-lg px-3 py-3 font-black text-[#099aa5]">{product.margin.toFixed(2)}%</td></tr>) : <tr><td colSpan={4} className="p-12 text-center text-[#887e73]">Sin productos registrados.</td></tr>}</tbody></table></div></section></div></div></AuthenticatedLayout>;
}
function money(value: number) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(value); }
