import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Notification = { id: number; type: string; title: string; body?: string | null; read_at?: string | null; created_at: string; branch?: { name: string } };
type Template = { id: number; code: string; title: string; body?: string | null; is_active: boolean };

export default function Index({ notifications, templates }: { notifications: Notification[]; templates: Template[] }) {
    const [selectedTemplate, setSelectedTemplate] = useState<Template | null>(templates[0] ?? null);
    const unread = notifications.filter(notification => !notification.read_at).length;
    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI　›　NOTIFICACIONES</p><h1 className="text-2xl font-black">Notificaciones</h1></div>}><Head title="Notificaciones" /><div className="grid gap-5 p-6 lg:p-8 xl:grid-cols-[minmax(0,1fr)_minmax(390px,0.9fr)]"><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">Notificaciones operativas</h2><span className="rounded-full bg-[#e7f9fb] px-3 py-1 text-xs font-black text-[#099aa5]">{unread} PENDIENTES</span></div>{notifications.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs font-black uppercase text-[#987e6b]"><tr><th className="p-3">FECHA</th><th className="p-3">TIPO</th><th className="p-3">SUCURSAL</th><th className="p-3">MENSAJE</th><th className="p-3">ESTADO</th></tr></thead><tbody>{notifications.map(notification => <tr key={notification.id} className={`border-t ${notification.read_at ? '' : 'bg-[#f3fdfd]'}`}><td className="p-3">{date(notification.created_at)}</td><td className="p-3 font-black">{type(notification.type)}</td><td className="p-3">{notification.branch?.name || 'Operación general'}</td><td className="p-3"><strong className="block">{notification.title}</strong><small className="text-[#687873]">{notification.body}</small></td><td className="p-3">{notification.read_at ? <span className="font-black text-[#2aad48]">LEÍDA</span> : <button type="button" onClick={() => router.post(route('notifications.read', notification.id), {}, { preserveScroll: true })} className="rounded-lg border border-[#099aa5] px-2 py-1 text-xs font-black text-[#099aa5]">MARCAR LEÍDA</button>}</td></tr>)}</tbody></table></div> : <Empty text="Sin registros" />}</section><section className="rounded-xl border border-[#e5dfd4] bg-white p-4"><h2 className="mb-4 text-lg font-black">Plantillas</h2><div className="space-y-3">{templates.map(template => <button type="button" key={template.id} onClick={() => setSelectedTemplate(template)} className={`w-full rounded-lg p-3 text-left ${selectedTemplate?.id === template.id ? 'border border-[#099aa5] bg-[#f4fffe]' : 'bg-[#fdfcf9]'}`}><p className="text-xs font-black uppercase text-[#987e6b]">{template.code}</p><p className="mt-1 font-black">{template.title}</p><small className={template.is_active ? 'text-[#2aad48]' : 'text-red-500'}>{template.is_active ? 'Activa' : 'Inactiva'}</small></button>)}</div>{selectedTemplate && <TemplateEditor key={selectedTemplate.id} template={selectedTemplate} />}</section></div></AuthenticatedLayout>;
}
function TemplateEditor({ template }: { template: Template }) { const form = useForm({ title: template.title, body: template.body ?? '', is_active: template.is_active }); const submit = (event: FormEvent) => { event.preventDefault(); form.put(route('notifications.templates.update', template.id), { preserveScroll: true }); }; return <form onSubmit={submit} className="mt-5 grid gap-3 border-t pt-4"><h3 className="font-black">Editar plantilla</h3><label className="grid gap-1 text-xs font-black text-[#987e6b]">TÍTULO<input value={form.data.title} onChange={event => form.setData('title', event.target.value)} className="rounded-lg border-[#d8d5ce]" /></label><label className="grid gap-1 text-xs font-black text-[#987e6b]">MENSAJE<textarea value={form.data.body} onChange={event => form.setData('body', event.target.value)} rows={3} className="rounded-lg border-[#d8d5ce]" /></label><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.data.is_active} onChange={event => form.setData('is_active', event.target.checked)} /> Plantilla activa</label><button disabled={form.processing} className="rounded-lg bg-[#099aa5] px-4 py-3 text-sm font-black text-white">{form.processing ? 'GUARDANDO...' : '▣　GUARDAR'}</button></form>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-40 place-items-center rounded-lg border border-dashed border-[#d8d5ce] text-sm font-bold text-[#887e73]">⚠　{text}</div>; }
function date(value: string) { return new Intl.DateTimeFormat('es-MX', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)); }
function type(value: string) { return ({ new_order: 'NUEVO PEDIDO', order_status: 'ESTADO DE PEDIDO', stock: 'INVENTARIO' } as Record<string, string>)[value] ?? value.toUpperCase(); }
