import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, useForm } from '@inertiajs/react';
import { FormEvent, ReactNode, useState } from 'react';

type Product = { id: number; name: string; sku: string; base_price: string; direct_cost?: string; gross_profit?: string; margin_percent?: string };
type InventoryItem = { id: number; name: string; code: string; unit: string; unit_cost: string };
type Recipe = { id: number; name: string; packaging_cost: string; other_cost: string; product: Product; ingredients: { id: number; quantity: string; item: InventoryItem }[] };

export default function Index({ recipes, products, inventoryItems }: { recipes: Recipe[]; products: Product[]; inventoryItems: InventoryItem[] }) {
    const [showRecipe, setShowRecipe] = useState(false); const [showIngredient, setShowIngredient] = useState(false);
    const recipeForm = useForm({ product_id: products[0]?.id?.toString() || '', name: '', packaging_cost: '0', other_cost: '0', is_active: true });
    const ingredientForm = useForm({ recipe_id: recipes[0]?.id?.toString() || '', inventory_item_id: inventoryItems[0]?.id?.toString() || '', quantity: '' });
    const saveRecipe = (event: FormEvent) => { event.preventDefault(); recipeForm.post(route('recipes.store'), { onSuccess: () => { recipeForm.reset(); setShowRecipe(false); } }); };
    const saveIngredient = (event: FormEvent) => { event.preventDefault(); if (ingredientForm.data.recipe_id) ingredientForm.post(route('recipes.ingredients.store', ingredientForm.data.recipe_id), { onSuccess: () => { ingredientForm.reset('quantity'); setShowIngredient(false); } }); };

    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI / RECETAS Y COSTOS</p><h1 className="text-2xl font-black">Recetas y costos</h1></div>}>
        <Head title="Recetas y costos" />
        <div className="space-y-5 p-6 lg:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[#687873]">Relaciona productos con insumos y calcula su costo directo, utilidad y margen.</p><div className="flex gap-2"><button type="button" onClick={() => setShowRecipe(!showRecipe)} className="rounded-lg border border-[#099aa5] px-4 py-2 text-sm font-black text-[#099aa5]">+ RECETA</button><button type="button" onClick={() => setShowIngredient(!showIngredient)} disabled={!recipes.length || !inventoryItems.length} className="rounded-lg bg-[#ffc400] px-4 py-2 text-sm font-black text-[#062947] disabled:opacity-50">+ INSUMO A RECETA</button></div></div>
            {showRecipe && <form onSubmit={saveRecipe} className="grid gap-3 rounded-xl border border-[#e5dfd4] bg-white p-5 md:grid-cols-2 lg:grid-cols-3"><h2 className="col-span-full text-lg font-black">Nueva receta</h2><Field label="Producto" error={recipeForm.errors.product_id}><select value={recipeForm.data.product_id} onChange={e => recipeForm.setData('product_id', e.target.value)}>{products.map(product => <option key={product.id} value={product.id}>{product.name} · {money(product.base_price)}</option>)}</select></Field><Field label="Nombre de receta" error={recipeForm.errors.name}><input value={recipeForm.data.name} onChange={e => recipeForm.setData('name', e.target.value)} placeholder="Receta latte mediano" /></Field><Field label="Costo empaque" error={recipeForm.errors.packaging_cost}><input type="number" min="0" step="0.01" value={recipeForm.data.packaging_cost} onChange={e => recipeForm.setData('packaging_cost', e.target.value)} /></Field><Field label="Otros costos directos" error={recipeForm.errors.other_cost}><input type="number" min="0" step="0.01" value={recipeForm.data.other_cost} onChange={e => recipeForm.setData('other_cost', e.target.value)} /></Field><div className="col-span-full flex justify-end"><button disabled={recipeForm.processing || !products.length} className="rounded-lg bg-[#099aa5] px-5 py-2 text-sm font-black text-white">GUARDAR RECETA</button></div></form>}
            {showIngredient && <form onSubmit={saveIngredient} className="grid gap-3 rounded-xl border border-[#e5dfd4] bg-white p-5 md:grid-cols-2 lg:grid-cols-3"><h2 className="col-span-full text-lg font-black">Agregar insumo</h2><Field label="Receta" error={ingredientForm.errors.recipe_id}><select value={ingredientForm.data.recipe_id} onChange={e => ingredientForm.setData('recipe_id', e.target.value)}>{recipes.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></Field><Field label="Insumo" error={ingredientForm.errors.inventory_item_id}><select value={ingredientForm.data.inventory_item_id} onChange={e => ingredientForm.setData('inventory_item_id', e.target.value)}>{inventoryItems.map(item => <option key={item.id} value={item.id}>{item.name} · {item.unit}</option>)}</select></Field><Field label="Cantidad por producto" error={ingredientForm.errors.quantity}><input type="number" min="0.001" step="0.001" value={ingredientForm.data.quantity} onChange={e => ingredientForm.setData('quantity', e.target.value)} /></Field><div className="col-span-full flex justify-end"><button disabled={ingredientForm.processing} className="rounded-lg bg-[#099aa5] px-5 py-2 text-sm font-black text-white">AGREGAR INSUMO</button></div></form>}
            <div className="grid gap-4 xl:grid-cols-2">{recipes.length ? recipes.map(recipe => <article key={recipe.id} className="rounded-xl border border-[#e5dfd4] bg-white p-5"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-black">{recipe.product.name}</h2><p className="text-sm text-[#687873]">{recipe.name}</p></div><div className="text-right"><p className="text-xs text-[#687873]">Precio</p><b>{money(recipe.product.base_price)}</b></div></div><div className="my-4 grid grid-cols-3 gap-2 rounded-lg bg-[#f7f3eb] p-3 text-center text-xs"><Value label="Costo directo" value={money(recipe.product.direct_cost || '0')} /><Value label="Utilidad" value={money(recipe.product.gross_profit || '0')} /><Value label="Margen" value={`${Number(recipe.product.margin_percent || 0).toFixed(1)}%`} /></div><div className="space-y-2">{recipe.ingredients.length ? recipe.ingredients.map(ingredient => <div key={ingredient.id} className="flex justify-between text-sm"><span>{ingredient.item.name} <small className="text-[#687873]">({ingredient.quantity} {ingredient.item.unit})</small></span><b>{money(Number(ingredient.quantity) * Number(ingredient.item.unit_cost))}</b></div>) : <p className="text-sm text-[#887e73]">Aún no tiene insumos. Agrégalos para calcular el costo.</p>}</div></article>) : <div className="col-span-full rounded-xl border border-dashed border-[#d8d5ce] p-14 text-center text-[#887e73]">Crea una receta para conectar un producto con sus insumos.</div>}</div>
        </div>
    </AuthenticatedLayout>;
}
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="grid gap-1 text-xs font-bold text-[#52635e]">{label}<span className="[&>input]:w-full [&>input]:rounded-lg [&>input]:border [&>input]:border-[#d8d5ce] [&>input]:px-3 [&>input]:py-2 [&>select]:w-full [&>select]:rounded-lg [&>select]:border [&>select]:border-[#d8d5ce] [&>select]:px-3 [&>select]:py-2">{children}</span><span className="min-h-4 text-[#e94250]">{error}</span></label>; }
function Value({ label, value }: { label: string; value: string }) { return <span><small className="block text-[#687873]">{label}</small><b>{value}</b></span>; }
function money(value: number | string) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(value)); }
