import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useMemo, useState } from 'react';

type Order = { id: number; folio: string; customer_name?: string; channel: string; fulfillment_type: string; status: string; total: string; payment_method?: string; placed_at?: string; created_at: string; notes?: string; branch: { name: string }; items: { id: number; quantity: number; product_name?: string; unit_price?: string; total?: string }[] };

export default function Index({ orders }: { orders: Order[] }) {
    const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<Order | null>(null);
    const visibleOrders = useMemo(() => orders.filter(order => (!status || order.status === status) && (!query || `${order.folio} ${order.customer_name || ''} ${order.branch.name}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))), [orders, query, status]);
    const exportOrders = () => { const rows = [['Folio', 'Cliente', 'Sucursal', 'Total', 'Pago', 'Estado', 'Hora'], ...visibleOrders.map(order => [order.folio, order.customer_name || 'Cliente móvil', order.branch.name, money(order.total), order.payment_method || '—', statusLabel(order.status), date(order.placed_at || order.created_at)])]; const csv = rows.map(row => row.map(value => `"${value}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = 'luzi-pedidos-filtrados.csv'; link.click(); URL.revokeObjectURL(link.href); };

    return <AuthenticatedLayout header={<div><p className="text-xs font-black tracking-wide text-[#099aa5]">LUZI　›　PEDIDOS</p><h1 className="text-2xl font-black">Pedidos</h1></div>}>
        <Head title="Pedidos" />
        <div className="space-y-5 p-6 lg:p-8">
            <section className="rounded-xl border border-[#e5dfd4] bg-white p-4">
                <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black">Pedidos en tiempo real</h2><div className="flex flex-wrap gap-2"><Link href={route('sales.index')} className="rounded-lg border border-[#099aa5] px-4 py-2 text-xs font-black text-[#099aa5]">VER VENTAS</Link><button type="button" onClick={exportOrders} className="rounded-lg bg-[#099aa5] px-4 py-2 text-xs font-black text-white">⇩　EXPORTAR</button></div></div>
                <div className="mb-4 grid gap-3 md:grid-cols-[1fr_220px]"><label className="flex h-11 items-center gap-2 rounded-lg border border-[#dce2e3] px-3 text-sm"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar folio, cliente o sucursal" className="w-full border-0 p-0 outline-none ring-0" /></label><select value={status} onChange={event => setStatus(event.target.value)} className="rounded-lg border-[#dce2e3] text-sm"><option value="">Todos los estados</option>{['pending', 'preparing', 'ready', 'completed', 'cancelled'].map(value => <option key={value} value={value}>{statusLabel(value)}</option>)}</select></div>
                <p className="mb-3 text-sm font-black text-[#687873]">{visibleOrders.length} pedidos visibles</p>
                <div className="overflow-x-auto"><table className="w-full min-w-[900px] border-separate border-spacing-y-2 text-left text-sm"><thead className="text-xs font-black uppercase text-[#987e6b]"><tr>{['Folio', 'Cliente', 'Sucursal', 'Total', 'Pago', 'Estado', 'Hora'].map(column => <th className="px-3" key={column}>{column}　›</th>)}</tr></thead><tbody>{visibleOrders.length ? visibleOrders.map(order => <tr key={order.id} onClick={() => setSelected(order)} className="cursor-pointer bg-[#fdfdfd] shadow-sm transition hover:bg-[#f1fcfb]"><td className="rounded-l-lg px-3 py-3"><strong className="block">{order.folio}</strong><small className="font-bold text-[#987e6b]">{order.channel} · {order.fulfillment_type}</small></td><td className="px-3 py-3 font-bold">{order.customer_name || 'Cliente móvil'}</td><td className="px-3 py-3 font-bold">{order.branch.name}</td><td className="px-3 py-3 font-black">{money(order.total)}</td><td className="px-3 py-3">{order.payment_method || '—'}</td><td className="px-3 py-3"><Status status={order.status} /></td><td className="rounded-r-lg px-3 py-3">{date(order.placed_at || order.created_at)}</td></tr>) : <tr><td colSpan={7} className="p-14 text-center text-[#887e73]">No hay pedidos todavía. Este módulo quedará conectado al endpoint de creación de pedidos de la app móvil.</td></tr>}</tbody></table></div>
            </section>
        </div>
        {selected && <OrderDetail order={selected} onClose={() => setSelected(null)} />}
    </AuthenticatedLayout>;
}

function OrderDetail({ order, onClose }: { order: Order; onClose: () => void }) {
    const [next, setNext] = useState(order.status); const options = [order.status, ...nextStatuses(order.status)];
    const updateStatus = () => { if (next !== order.status) router.put(route('orders.status.update', order.id), { status: next }, { onSuccess: onClose }); };
    return <div className="fixed inset-0 z-50 flex justify-end bg-[#062947]/40"><aside className="h-full w-full max-w-md overflow-y-auto bg-[#fdfbf6] p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-xs font-black text-[#099aa5]">PEDIDO</p><h2 className="text-xl font-black">{order.folio}</h2></div><button type="button" onClick={onClose} className="rounded-lg border px-3 py-2 text-xs font-black">× CERRAR</button></div><div className="space-y-3 rounded-lg border bg-white p-4 text-sm"><p><b>Cliente:</b> {order.customer_name || 'Cliente móvil'}</p><p><b>Sucursal:</b> {order.branch.name}</p><p><b>Canal:</b> {order.channel}</p><p><b>Tipo de pedido:</b> {order.fulfillment_type}</p><p><b>Pago:</b> {order.payment_method || '—'}</p><p><b>Total:</b> {money(order.total)}</p>{order.notes && <p><b>Notas:</b> {order.notes}</p>}</div><h3 className="mb-3 mt-6 font-black">Productos</h3><div className="space-y-2">{order.items.map(item => <article className="rounded-lg border bg-white p-3" key={item.id}><strong>{item.quantity}× {item.product_name || 'Producto'}</strong><span className="float-right font-black">{item.total ? money(item.total) : '—'}</span></article>)}</div><div className="mt-6 rounded-lg border bg-white p-4"><label className="grid gap-2 text-xs font-black text-[#987e6b]">CAMBIAR ESTADO<select value={next} onChange={event => setNext(event.target.value)} className="rounded-lg border-[#dce2e3] text-sm">{options.map(value => <option value={value} key={value}>{statusLabel(value)}</option>)}</select></label><button type="button" disabled={next === order.status} onClick={updateStatus} className="mt-3 w-full rounded-lg bg-[#099aa5] py-3 text-xs font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300">ACTUALIZAR PEDIDO</button></div></aside></div>;
}

function Status({ status }: { status: string }) { const tones: Record<string, string> = { pending: 'bg-[#fff0cf] text-[#a16000]', preparing: 'bg-[#ffe7c6] text-[#b85c00]', ready: 'bg-[#daf5df] text-[#1e843b]', completed: 'bg-[#e2f5ed] text-[#167a5d]', cancelled: 'bg-[#ffe0e4] text-[#c52d42]' }; return <span className={`rounded-full px-2.5 py-1 text-xs font-black ${tones[status] || 'bg-slate-100 text-slate-600'}`}>{statusLabel(status)}</span>; }
function statusLabel(status: string) { return ({ pending: 'Pendiente', preparing: 'En preparación', ready: 'Listo', completed: 'Completado', cancelled: 'Cancelado' } as Record<string, string>)[status] || status; }
function nextStatuses(status: string) { return ({ pending: ['preparing', 'cancelled'], preparing: ['ready', 'cancelled'], ready: ['completed', 'cancelled'], completed: [], cancelled: [] } as Record<string, string[]>)[status] || []; }
function money(value: string) { return new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' }).format(Number(value)); }
function date(value: string) { return new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
